name: FreeBSD Go Build

on:
  push:
    branches: [ "test-workflow" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.11'

    - name: Set up FreeBSD environment
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y go
          pkg install -y git

    - name: Build
      env:
        GOPATH: /home/runner/go
      run: |
        cd $GITHUB_WORKSPACE
        pwd
        ls -la
        cd cmd/dashboard
        go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=0.18.8"
        mkdir -p ~/nezhapanel
        cp dashboard ~/nezhapanel/
        cp -r ../../resource ~/nezhapanel/
        rm ~/nezhapanel/resource/resource.go
        mkdir -p ~/nezhapanel/data
        cp ../../script/config.yaml ~/nezhapanel/data/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nezhapanel
        path: ~/nezhapanel
