name: Test Build Nezha
on:
  workflow_dispatch:
  push:
    branches:
      - test-workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.11'
    
    - name: Modify go.mod for pure Go SQLite
      run: |
        go mod edit -replace github.com/mattn/go-sqlite3=github.com/glebarez/go-sqlite@latest
        go mod tidy
    
    - name: Build for FreeBSD AMD64
      env:
        GOOS: freebsd
        GOARCH: amd64
        CGO_ENABLED: 0
      run: |
        cd cmd/dashboard
        go build -ldflags="-s -w -X github.com/naiba/nezha/service/singleton.Version=$(git describe --tags --always)" -o dashboard
    
    - name: Prepare files
      run: |
        mkdir nezhapanel
        cp cmd/dashboard/dashboard nezhapanel/
        cp -r resource nezhapanel/
        rm nezhapanel/resource/resource.go
        mkdir nezhapanel/data
        cp script/config.yaml nezhapanel/data/config.yaml
    
    - name: Create ZIP archive
      run: zip -r nezha-freebsd-amd64.zip nezhapanel
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nezha-freebsd-amd64
        path: nezha-freebsd-amd64.zip
