name: Build Nezha on FreeBSD

on:
  push:
    branches: [ "test-workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up FreeBSD VM
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        mem: 4096
        prepare: |
          pkg install -y go git

    - name: Build Nezha
      run: |
        export GOROOT=/usr/local/go
        export PATH=$PATH:$GOROOT/bin
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin
        
        cd cmd/dashboard
        go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=0.18.8"
        
        mkdir ~/nezhapanel && cd ~/nezhapanel
        cp ~/work/nezha/nezha/cmd/dashboard/dashboard ~/nezhapanel/dashboard
        cp -r ~/work/nezha/nezha/resource ~/nezhapanel/resource
        rm ~/nezhapanel/resource/resource.go
        mkdir ~/nezhapanel/data
        cp ~/work/nezha/nezha/script/config.yaml ~/nezhapanel/data/config.yaml
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nezha-freebsd
        path: ~/nezhapanel
