name: Build Nezha using Docker

on:
  push:
    branches: [ "test-workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Nezha
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app golang:1.21 /bin/bash -c '
          export GOPROXY=https://goproxy.io,direct
          go version
          go env
          cd /app
          go mod download
          cd cmd/dashboard
          CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w -X github.com/naiba/nezha/service/singleton.Version=0.18.8"
        '

    - name: Prepare nezha panel
      run: |
        mkdir ~/nezhapanel
        cp ${{ github.workspace }}/cmd/dashboard/dashboard ~/nezhapanel/dashboard
        cp -r ${{ github.workspace }}/resource ~/nezhapanel/resource
        rm ~/nezhapanel/resource/resource.go
        mkdir ~/nezhapanel/data
        cp ${{ github.workspace }}/script/config.yaml ~/nezhapanel/data/config.yaml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nezha-freebsd
        path: ~/nezhapanel
