name: Build NezhaPanel

on:
  workflow_dispatch:
  push:
    branches:
      - test-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: freebsd/amd64

    - name: Build for FreeBSD amd64
      run: |
        docker run --rm \
          -v "$PWD":/usr/src/myapp \
          -w /usr/src/myapp \
          freebsd:13.1 \
          /bin/sh -c "pkg install -y go git && \
                      GOOS=freebsd GOARCH=amd64 CGO_ENABLED=1 \
                      go build -ldflags='-s -w --extldflags \"-static -fpic\" -X github.com/naiba/nezha/service/singleton.Version=0.18.8' \
                      -o dashboard ./cmd/dashboard"

    - name: Prepare output directory
      run: |
        mkdir -p ~/nezhapanel
        cp ./dashboard ~/nezhapanel/dashboard
        cp -r ./resource ~/nezhapanel/resource
        rm ~/nezhapanel/resource/resource.go
        mkdir ~/nezhapanel/data
        cp ./script/config.yaml ~/nezhapanel/data/config.yaml

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NezhaPanel
        path: ~/nezhapanel
