name: FreeBSD Go Build

on:
  push:
    branches: [ "test-workflow" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.11'

    - name: Set up FreeBSD environment
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y go
          pkg install -y git
          
    - name: Build
      run: |
        cd cmd/dashboard
        go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=0.18.8"
        mkdir ~/nezhapanel && cd ~/nezhapanel
        cp ~/work/your-repo-name/your-repo-name/cmd/dashboard/dashboard ~/nezhapanel/dashboard
        cp -r ~/work/your-repo-name/your-repo-name/resource ~/nezhapanel/resource
        rm ~/nezhapanel/resource/resource.go
        mkdir ~/nezhapanel/data
        cp ~/work/your-repo-name/your-repo-name/script/config.yaml ~/nezhapanel/data/config.yaml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nezhapanel
        path: ~/nezhapanel
