name: Build Nezha on FreeBSD

on:
  push:
    branches:
      - test-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build on FreeBSD
      uses: cross-platform-actions/action@v0.21.0
      with:
        operating_system: freebsd
        version: '13.2'
        run: |
          sudo pkg update -f
          sudo pkg install -y go git
          export GOROOT=/usr/local/go
          export PATH=$PATH:/usr/local/go/bin
          export CGO_ENABLED=1
          cd cmd/dashboard
          go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=0.18.8"
          mkdir -p ~/nezhapanel
          cp dashboard ~/nezhapanel/dashboard
          cp -r ${{ github.workspace }}/resource ~/nezhapanel/resource
          rm ~/nezhapanel/resource/resource.go
          mkdir -p ~/nezhapanel/data
          cp ${{ github.workspace }}/script/config.yaml ~/nezhapanel/data/config.yaml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nezha-freebsd-amd64
        path: ~/nezhapanel
