name: Build Nezha on FreeBSD

on:
  push:
    branches:
      - test-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: freebsd/freebsd-ci:13.2-release
      options: --cpus 2
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      run: |
        pkg update -f
        pkg install -y go git

    - name: Set Go environment
      run: |
        echo "export GOROOT=/usr/local/go" >> $HOME/.profile
        echo "export PATH=$PATH:/usr/local/go/bin" >> $HOME/.profile
        echo "export CGO_ENABLED=1" >> $HOME/.profile
        source $HOME/.profile

    - name: Build Nezha
      run: |
        cd cmd/dashboard
        go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=0.18.8"
        mkdir ~/nezhapanel
        cd ~/nezhapanel
        cp ~/work/nezha/nezha/cmd/dashboard/dashboard ~/nezhapanel/dashboard
        cp -r ~/work/nezha/nezha/resource ~/nezhapanel/resource
        rm ~/nezhapanel/resource/resource.go
        mkdir ~/nezhapanel/data
        cp ~/work/nezha/nezha/script/config.yaml ~/nezhapanel/data/config.yaml

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nezha-freebsd-amd64
        path: ~/nezhapanel
