name: Build NezhaPanel

on:
  workflow_dispatch:
  push:
    branches:
      - test-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x

    - name: Build for FreeBSD amd64
      run: |
        GOOS=freebsd GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-linux-musl-gcc \
        go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=0.18.8" \
        -o dashboard ./cmd/dashboard

    - name: Prepare output directory
      run: |
        mkdir -p ~/nezhapanel
        cp ./dashboard ~/nezhapanel/dashboard
        cp -r ./resource ~/nezhapanel/resource
        rm ~/nezhapanel/resource/resource.go
        mkdir ~/nezhapanel/data
        cp ./script/config.yaml ~/nezhapanel/data/config.yaml

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NezhaPanel
        path: ~/nezhapanel
