name: Build NezhaPanel

on:
  workflow_dispatch:
  push:
    branches:
      - test-workflow

jobs:
  build:
    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Build on FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y go git
        run: |
          go version
          go env
          export GOPROXY=https://goproxy.io,direct
          cd ${{ github.workspace }}
          go mod download
          cd cmd/dashboard
          CGO_ENABLED=1 go build -buildvcs=false -ldflags="-s -w -X github.com/naiba/nezha/service/singleton.Version=0.18.8"

    - name: Prepare nezha panel
      run: |
        mkdir ~/nezhapanel
        cp ${{ github.workspace }}/cmd/dashboard/dashboard ~/nezhapanel/dashboard
        cp -r ${{ github.workspace }}/resource ~/nezhapanel/resource
        rm ~/nezhapanel/resource/resource.go
        mkdir ~/nezhapanel/data
        cp ${{ github.workspace }}/script/config.yaml ~/nezhapanel/data/config.yaml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nezha-freebsd
        path: ~/nezhapanel
