name: Test Build Nezha
on:
  workflow_dispatch:
  push:
    branches:
      - test-workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.11'
    
    - name: Install FreeBSD cross-compilation toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    
    - name: Build for FreeBSD AMD64
      env:
        GOOS: freebsd
        GOARCH: amd64
        CGO_ENABLED: 1
        CC: aarch64-linux-gnu-gcc
      run: |
        cd cmd/dashboard
        go build -ldflags="-s -w -X github.com/naiba/nezha/service/singleton.Version=$(git describe --tags --always)" -o dashboard
    
    - name: Prepare files
      run: |
        mkdir nezhapanel
        cp cmd/dashboard/dashboard nezhapanel/
        cp -r resource nezhapanel/
        rm nezhapanel/resource/resource.go
        mkdir nezhapanel/data
        cp script/config.yaml nezhapanel/data/config.yaml
    
    - name: Create archive
      run: tar -czvf nezha-freebsd-amd64.tar.gz nezhapanel
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nezha-freebsd-amd64
        path: nezha-freebsd-amd64.tar.gz
