name: Build and Package Nezha

on:
  push:
    branches:
      - test-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: freebsd:12.2
      options: --privileged  # 需要特权模式以运行某些 FreeBSD 命令

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.11

      - name: Install dependencies
        run: |
          pkg install -y git go
          go env -w GO111MODULE=on
          go mod download

      - name: Build Nezha
        run: |
          cd cmd/dashboard
          go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=0.18.8"

      - name: Package Nezha
        run: |
          mkdir -p ~/nezhapanel
          cp cmd/dashboard/dashboard ~/nezhapanel/dashboard
          cp -r resource ~/nezhapanel/resource
          rm ~/nezhapanel/resource/resource.go
          mkdir ~/nezhapanel/data
          cp script/config.yaml ~/nezhapanel/data/config.yaml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nezhapanel
          path: ~/nezhapanel
